import type { Metadata } from "next";
import { Inter } from 'next/font/google'
import "./globals.css";
import { DefaultProvider } from "./components/defaul-provider";

const inter = Inter({
  weight:["300","400", "500", "600"], 
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}`}
      >
        <DefaultProvider>
          {children}
        </DefaultProvider>
      </body>
    </html>
  );
}
